### ISSUE TITLE
Could not install via NuGet

### ISSUE THREAD

**Issue by rchibnik** [upta/pubsub#10]
Visual Studio 2012
WinForms .NET 4.5 project .
Tried to install via NuGet and got the error:
'PubSub' could not be installed beacause it is not compatable with any project in the solution. The package doesn't target any framework.

Works fine by deploying the DLL using add reference.

**Comment by upta** [comment]
That's very bizarre... I wasn't able to duplicate on my machine. :( Made a brand new WinForms .Net 4.5 project in VS 2012 and was able to install it just fine via the Package Manager Console.

http://prntscr.com/dwufah

**Comment by upta** [comment]
Haven't heard anything about this in a while, so closing for now
