### ISSUE TITLE
NETStandard?

### ISSUE THREAD

**Issue by dazinator** [upta/pubsub#12]
Have you thought about targeting NETStandard now?

**Comment by upta** [comment]
There's actually an open PR for that; I was just out of town and didn't have a chance to merge it yet.  Will see about doing that today

**Comment by dazinator** [comment]
Oh yeah! Sorry I hadn't noticed that :-)

**Comment by upta** [comment]
No worries, served as a good reminder that I needed to look at it :)

**Comment by Zaid-Safadi** [comment]
Hi @upta , do you have a timeline on when the .NET Standard PR will be merged? It would also be great if it is possible to target a lower .NET Standard version <=1.3

**Comment by upta** [comment]
Been swamped, sorry! I'll give #13 a build tomorrow and if everything is kosher I'll merge/publish. That one targets .Net standard 1.1, too

**Comment by upta** [comment]
I merged and published #13 to nuget as version 2.0.0.  Still messing with AppVeyor to see if I can get it to build with it (works fine with my local VS2017).  Let me know if you guys have any issues, thanks!

**Comment by dazinator** [comment]
Looks good! I'll try it out in my netstandard (xamarin) app.
