### ISSUE TITLE
Subscribing multiple times causes the action to be triggered more than once.

### ISSUE THREAD

**Issue by mavera** [upta/pubsub#14]
When we add subscribe code to somewhere like activity onCreate, page load etc, it's possible for this code to be called multiple times. Than, this causes the message action being called multiple times. 

I think there should be a precaution or at least an option to prevent this situation.

**Comment by upta** [comment]
There are definitely valid scenarios in which you'd want to subscribe multiple times to the same kind of event.

In those kinds of "OnCreate" scenarios it's generally a good practice to unsubscribe inside your "OnDestroy"

On Nov 27, 2017 11:06 PM, Serdar <notifications@github.com> wrote:

When we add subscribe code to somewhere like activity onCreate, page load etc, it's possible for this code to be called multiple times. Than, this causes the message action being called multiple times.

I think there should be a precaution or at least an option to prevent this situation.

**Comment by mavera** [comment]
Ok then, I'll reevaluate my case and find a solution. Thanks
