### ISSUE TITLE
Why .NET 4.5?

### ISSUE THREAD

**Issue by dhilgarth** [upta/pubsub#15]
Nice little library! Straight to the point.

But I see no reason why it works only from .NET 4.5 onwards. Why not make it work from 3.5 or at least 4.0?

**Comment by upta** [comment]
It was originally a PCL library (I build it for my own use in Xamarin Android, tbh).

It was later ported to .NetStandard 1.1, which has an equivalent .Net verison of 4.5 (https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

As it is, .Net 4.5 will be 6 years old in August ;)

I imagine it would compile just fine against a lower .Net version if someone needed it for a legacy project.  It doesn't exactly get many updates so it unlikely they'd miss much using a custom build :)

**Comment by dhilgarth** [comment]
Yeah, as it happens I wanted to use it in a 4.0 project. But I simply copied the two files to my project ;)
