### ISSUE TITLE
.Net Standard 2.0

### ISSUE THREAD

**Issue by mariusmuntean** [upta/pubsub#17]
Thanks for the great library!
When using the library NuGet pulls in a ton of other libraries. 

Could you also provide a version that depends on .Net Standard 2.0? I think that would alleviate this issue a lot.

**Comment by upta** [comment]
I've been mulling that over for a bit because of David Fowler's constant promptings that libraries should start using 2.0 as their baseline ;)

I've gotta get on that PR here anyway (been a slacker), I'll look into it when I verify that.

Thanks!

**Comment by upta** [comment]
Alrighty, I've merged the latest PR, did a little code cleanup, multi-targeted netstandard1.1 and netstandard 2.0 and updated the package on Nuget (https://www.nuget.org/packages/PubSub/2.1.0)

Let me know if you run into any issues, thanks!
