### ISSUE TITLE
Add StrongName signing

### ISSUE THREAD

**Issue by stkaratz** [upta/pubsub#18]
Can you add signing so it can be referenced by signed assemblies?

**Comment by upta** [comment]
I'll take a look into this.  Sorry, saw you created the issue and totally spaced it!

**Comment by stkaratz** [comment]
Hello. Don't mean to bug you, but are you planning on addressing this soon? I'm asking because I would love to know if we should keep using the package 👍

**Comment by upta** [comment]
Alrighty @stkaratz , I spent some time and got the strong naming added.  It's not something I've ever done before, so I'd like for you to build it and give it a test run and make sure that it's working how you expect.

Once I get confirmation, I'll update the Nuget package as well.

Thanks!

**Comment by stkaratz** [comment]
Thank you so much for your replies ;)

**Comment by upta** [comment]
@stkaratz were you able to give this version a try to make sure it serves your needs?

**Comment by stkaratz** [comment]
@upta Good morning :) I did test master here and it works perfectly. If it's not much trouble, when are you planning on publishing this on nuget?

**Comment by upta** [comment]
Sorry about the delay, holidays slowed things down :)

Published to Nuget as 2.2.0

**Comment by number4400** [comment]
Hi Upta, 
I have a question, on Nuget you have published 2.2.0 versin, but in your code version is 3.0.0.
Version 2.2.0 has issue with strong name on my project.
I builded version 3.0.0 and referenced it in the project, and is working fine. 
Maybe it would be good to publish the 3.0.0 version?

**Comment by upta** [comment]
@number4400 You know, I thought that was odd when I did it (vaguely remembered bumping the version to 3.0.0; apparently I should have second-guessed myself when I discarded that thought ;)

I'll get that updated as soon as I can, hopefully later on today.

Thanks for the heads up!
