### ISSUE TITLE
Hub calls handlers subscribed to a base class when an instance from derived class is published

### ISSUE THREAD

**Issue by dzholmukhanov** [upta/pubsub#8]
Not sure if it's an issue. Suppose I have 2 classes which I use to communicate: base and derived. Listener that is subscribed to the base class with a handler method gets called when an instance of the derived class is published.

**Comment by upta** [comment]
Been a while, so I didn't remember all the details, but a contributor added this specifically in https://github.com/upta/pubsub/pull/2

This was so you could have more generic, catch-all event handlers

**Comment by dzholmukhanov** [comment]
Sorry. Didn't notice that. Thanks for a great library!
