### ISSUE TITLE
Publish scope

### ISSUE THREAD

**Issue by WattsC-90** [upta/pubsub#9]
Hi, 
Looks like a nice clean library, good job! 
Can you tell me what scope this works on, is it possible to use this nuget package to communicate across a network(ethernet)? Or is it only intended for single system/pc use? 
Thanks!

**Comment by upta** [comment]
Thanks :)  No networking, it's just setup for communication between disparate parts of an app

**Comment by WattsC-90** [comment]
Ahh gotcha! Thanks for the quick response
